### ISSUE TITLE
proxy problem

### ISSUE THREAD

**Issue by scar17off** [dimdenGD/OWOP.js_v2#11]
думаю можно на русском да говорить?

значит я бота пишу, хочу в него прокси заconnectить, пробовал твой пример из закрытого вопроса он оказывается не для **консоли**. поговорив с коммьюнити создателей ботов я узнал что если подключать прокси к JS ботам то нужно вводить какойто никнейм и пароль. как тогда работает polybius? в нем список из 5000 таких прокси чтоли. прошу потратить время на меня, и описать примеры кода. ведь если я узнаю как включить прокси в бота то OWOP не взорвется.

**Comment by dimdenGD** [comment]
не знаю про какой никнейм и пароль идёт речь, прокси "в консоле" (как раз через консоль обычно всё и запускается) должны работать нормально, главное найти нормальные прокси в интернете

**Comment by scar17off** [comment]
вы не написали Browser OJS пример запуска бота с прокси. Возможно я дебил, но в OPM не существует пакета HttpsProxyAgent.

**Comment by dimdenGD** [comment]
это пример для node.js

**Comment by scar17off** [comment]
> это пример для node.js

вы возможно уходите от написания примера бота с прокси, я правильно мыслю?
