### ISSUE TITLE
requestChunk promise instability

### ISSUE THREAD

**Issue by TotallyMehis** [dimdenGD/OWOP.js_v2#6]
Not really expecting this to be fixed. Just documenting in case somebody else is having similar issues.

---

Using requestChunk like this causes chunks to never make it into the callback:
```javascript
// Request a bunch of chunks.
for (...) {
    Client.world.requestChunk(x, y).then((chunk) => {
        // Do chunk specific stuff...
    });
}
```

Instead has to be written like this to capture all:
```javascript
const retrievedChunk = (x, y, chunk, protected) => {
    // Do chunk specific stuff...
}

Client.on("chunk", retrievedChunk);

// Request a bunch of chunks.
for (...) {
    Client.world.requestChunk(x, y);
}

await waitTillAllChunksRetrieved();
Client.off("chunk", retrievedChunk);

```

---
My hypothesis is that the temporary event listener is closed (`OJS.off("chunk", fn)`) for a bunch of chunks whenever the frame's first chunk has been retrieved. Here:
https://github.com/dimdenGD/OWOP.js_v2/blob/75c64174eaecd929efcdb2a88002dd1e68baa5c4/index.js#L397-L402

**Comment by rimbas** [comment]
Change the way callback functions are stored in `_events` from `[]` to `new Set()` and all respective methods for event emitter. Seems to work for me in my fork.

**Comment by dimdenGD** [comment]
you can make pull request

**Comment by OptoCloud** [comment]
@rimbas Can you create a pull request, your changes work nicely.
Also why did you decide to remove the ``client.once()`` event registration function?

**Comment by dimdenGD** [comment]
fixed in #7

**Comment by OptoCloud** [comment]
Will you bump the npm package to this commit or is it done automatocally? 🤔

**Comment by dimdenGD** [comment]
> Will you bump the npm package to this commit or is it done automatocally? 🤔

already did
